### ISSUE TITLE
Tenants

### ISSUE THREAD

**Issue by rosimildo** [mmirzaee/userist#1]
Hi there!
Thanks for the Userist package. It looks promising. 

I poked around with it, and I have some questions:

Could you explain in a nutshell what are the use cases for Tenants ?

I can see the concepts about Roles, and Meta Data.  Meta data, being dynamic properties that could be attached to an user, like addresses, phones, etc.

I have been unable to fully understand how the Tenants aspect would be used. I have some guesses, but might be limited.

Do you have any insights about "Audits" ? I mean by this,  last logins with IP info, etc.

Lastly, any user interface very simplistic exists ?

Thanks.

**Comment by mmirzaee** [comment]
Hi Rosimildo,

I made Userist as a service for managing users inside a microservice system. I had a plan for using this for a system that allowed customers to have their own users registered and assign proper roles to each of them. for example, look at Datadog or any other system that you can declare sub-accounts. Let's name it service X. Service X allows you to have the application on your own domain name (Y.com) or simply on subdomains (Foo.X.com). with this "Tenants" concept we can have a user with **manager** role inside (Foo.X.com) and that user can have **Administrator** role in (Bar.X.com) or even a simple **subscriber** role in (Y.com). "Tenants" are there for handling this kind of situation.

I'm glad someone found it useful. Don't hesitate to ask me any questions about it.

Best
